### ISSUE TITLE
Where to install inference models?

### ISSUE THREAD

**Issue by CGAlei** [Ilshidur/rvc-v2-crepe-docker#2]
i will like to test morgan freeman boice, but i dont know hoq to get into the folder to paste it.

**Comment by CGAlei** [comment]
i installed your image using docker in ubuntu, installed well, but cant access where the inferece models are located. until now i dont have any model.

**Comment by Ilshidur** [comment]
Hello.

If you're running the container using the recommended commands in the README, you should be able to add your voice in the `weights` directory that Docker mounts.

I added some docs in the README : https://github.com/Ilshidur/rvc-v2-crepe-docker#exposed-volumes
